### ISSUE TITLE
AssertionError: cant parse version xyz

### ISSUE THREAD

**Issue by bavovanachte** [pypa/setuptools-scm#292]
Hi,

One of our python projects uses the setuptools_scm tooling, but has started failing for versions > 2.1.0.

```
sphinx-latest runtests: commands[1] | mlx-warnings --sphinx --maxwarnings 7 --minwarnings 7 .tox/doc_html.log
  /home/travis/build/melexis/sphinx-traceability-extension$ /home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/bin/mlx-warnings --sphinx --maxwarnings 7 --minwarnings 7 .tox/doc_html.log 
/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/git.py:68: UserWarning: "/home/travis/build/melexis/sphinx-traceability-extension" is shallow and may cause errors
  warnings.warn('"%s" is shallow and may cause errors' % (wd.path,))
/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/version.py:92: UserWarning: tag 'V2.5.2' no version found
  warnings.warn("tag %r no version found" % (tag,))
Traceback (most recent call last):
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/bin/mlx-warnings", line 7, in <module>
    from mlx.warnings import main
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/mlx/warnings.py", line 16, in <module>
    __version__ = get_version()
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 135, in get_version
    parsed_version = _do_parse(config)
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 88, in _do_parse
    config, "setuptools_scm.parse_scm"
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 45, in _version_from_entrypoint
    version = _call_entrypoint_fn(config, ep.load())
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 33, in _call_entrypoint_fn
    return fn(config.absolute_root, config=config)
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/git.py", line 131, in parse
    branch=branch,
  File "/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/lib/python3.7/site-packages/setuptools_scm/version.py", line 184, in meta
    assert parsed_version is not None, "cant parse version %s" % tag
AssertionError: cant parse version V2.5.2
ERROR: InvocationError for command '/home/travis/build/melexis/sphinx-traceability-extension/.tox/sphinx-latest/bin/mlx-warnings --sphinx --maxwarnings 7 --minwarnings 7 .tox/doc_html.log' (exited with code 1)
```

No errors are thrown when using version 2.1.0. Could you give some pointers on what might cause this?

The issue in the warnings plugin project itself: https://github.com/melexis/warnings-plugin/issues/68

**Comment by RonnyPfannschmidt** [comment]
this relates to #284 which was fixed in #285 and was part of te pulled 3.0.3 release
until i find the time to fix the automated release process i cant release a correct v3.0.4

**Comment by bavovanachte** [comment]
Oops, sorry. Should have checked more carefully. 

Any idea on when that will be? Just to get an idea of whether it would then be better to start fixing the version to 2.1.0 in our CI to get unblocked.

**Comment by RonnyPfannschmidt** [comment]
@bavovanachte i want to get it done today, but personal matter might stop me, so it may be reasonable to pin it directly and revisit the pin after the release was done

**Comment by bavovanachte** [comment]
Ok, thanks for the quick reply!

**Comment by RonnyPfannschmidt** [comment]
fix is released, thanks for the patience

**Comment by bavovanachte** [comment]
I've tried with version 3.0.4, but I'm still getting the exact same error. The latest log: https://travis-ci.org/melexis/sphinx-traceability-extension/jobs/408654714 (there you can see it's using 3.0.4)

**Comment by RonnyPfannschmidt** [comment]
@bavovanachte thanks for the note - i noticed that the default regex we have in place only matches `v` and not `V` as marker character, i'll fix it swiftly
